%bcond_without tests
%bcond_without weak_deps

%global __os_install_post %(echo '%{__os_install_post}' | sed -e 's!/usr/lib[^[:space:]]*/brp-python-bytecompile[[:space:]].*$!!g')
%global __provides_exclude_from ^/opt/ros/rolling/.*$
%global __requires_exclude_from ^/opt/ros/rolling/.*$

Name:           ros-rolling-cartographer-ros
Version:        1.0.9003
Release:        3%{?dist}%{?release_suffix}
Summary:        ROS cartographer_ros package

License:        Apache 2.0
URL:            https://github.com/ros2/cartographer_ros
Source0:        %{name}-%{version}.tar.gz

Requires:       lua-devel
Requires:       pcl-devel
Requires:       ros-rolling-cartographer
Requires:       ros-rolling-cartographer-ros-msgs
Requires:       ros-rolling-nav-msgs
Requires:       ros-rolling-rclcpp
Requires:       ros-rolling-sensor-msgs
Requires:       ros-rolling-tf2
Requires:       ros-rolling-tf2-msgs
Requires:       ros-rolling-tf2-ros
Requires:       ros-rolling-visualization-msgs
Requires:       yaml-cpp-devel
Requires:       ros-rolling-ros-workspace
BuildRequires:  eigen3-devel
BuildRequires:  lua-devel
BuildRequires:  pcl-devel
BuildRequires:  ros-rolling-ament-cmake
BuildRequires:  ros-rolling-cartographer
BuildRequires:  ros-rolling-cartographer-ros-msgs
BuildRequires:  ros-rolling-nav-msgs
BuildRequires:  ros-rolling-pcl-conversions
BuildRequires:  ros-rolling-rclcpp
BuildRequires:  ros-rolling-sensor-msgs
BuildRequires:  ros-rolling-tf2
BuildRequires:  ros-rolling-tf2-eigen
BuildRequires:  ros-rolling-tf2-msgs
BuildRequires:  ros-rolling-tf2-ros
BuildRequires:  ros-rolling-urdfdom-headers
BuildRequires:  ros-rolling-visualization-msgs
BuildRequires:  yaml-cpp-devel
BuildRequires:  ros-rolling-ros-workspace
Provides:       %{name}-devel = %{version}-%{release}
Provides:       %{name}-doc = %{version}-%{release}
Provides:       %{name}-runtime = %{version}-%{release}

%description
Cartographer is a system that provides real-time simultaneous localization and
mapping (SLAM) in 2D and 3D across multiple platforms and sensor configurations.
This package provides Cartographer's ROS integration.

%prep
%autosetup

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/rolling/setup.sh" ]; then . "/opt/ros/rolling/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake3 \
    -UINCLUDE_INSTALL_DIR \
    -ULIB_INSTALL_DIR \
    -USYSCONF_INSTALL_DIR \
    -USHARE_INSTALL_PREFIX \
    -ULIB_SUFFIX \
    -DCMAKE_INSTALL_PREFIX="/opt/ros/rolling" \
    -DAMENT_PREFIX_PATH="/opt/ros/rolling" \
    -DCMAKE_PREFIX_PATH="/opt/ros/rolling" \
    -DSETUPTOOLS_DEB_LAYOUT=OFF \
    ..

%make_build

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/rolling/setup.sh" ]; then . "/opt/ros/rolling/setup.sh"; fi
%make_install -C obj-%{_target_platform}

%if 0%{?with_tests}
%check
# Look for a Makefile target with a name indicating that it runs tests
TEST_TARGET=$(%__make -qp -C obj-%{_target_platform} | sed "s/^\(test\|check\):.*/\\1/;t f;d;:f;q0")
if [ -n "$TEST_TARGET" ]; then
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/rolling/setup.sh" ]; then . "/opt/ros/rolling/setup.sh"; fi
CTEST_OUTPUT_ON_FAILURE=1 \
    %make_build -C obj-%{_target_platform} $TEST_TARGET || echo "RPM TESTS FAILED"
else echo "RPM TESTS SKIPPED"; fi
%endif

%files
/opt/ros/rolling

%changelog
* Fri Mar 26 2021 Chris Lalancette <clalancette@openrobotics.org> - 1.0.9003-3
- Autogenerated by Bloom

* Fri Mar 12 2021 Chris Lalancette <clalancette@openrobotics.org> - 1.0.9003-2
- Autogenerated by Bloom

* Mon Mar 08 2021 Chris Lalancette <clalancette@openrobotics.org> - 1.0.9003-1
- Autogenerated by Bloom

